### ISSUE TITLE
You need to also install package xlrd

### ISSUE THREAD

**Issue by martinsweitzer** [WenjieZ/pokemongo#1]
Fresh install of python 3.7.2

After pip installing numpy   and pandas  

you will need to all  pip install xlrd

**Comment by WenjieZ** [comment]
This may be because `pandas.read_excel` use `xlrd` but doesn't make it as a dependency.

**Comment by WenjieZ** [comment]
See this: https://github.com/pandas-dev/pandas/issues/14673

**Comment by WenjieZ** [comment]
Solved in #4
