### ISSUE TITLE
using most recent version of pandas results in column mismatch

### ISSUE THREAD

**Issue by martinsweitzer** [WenjieZ/pokemongo#2]
python 3.7.2
Successfully installed pandas-0.24.2 python-dateutil-2.8.0 pytz-2018.9 six-1.12.0

Will result in a column mismatch error when running.

C:\Python3\python.exe pokemongo.py Traceback (most recent call last): File "pokemongo.py", line 7, in <module> , skiprows=[163], usecols=[4, 9, 16, 17, 19, 20, 21], names=['Final', 'Type1','Type2','Atk','Def','Sta']) File "C:\Python3\lib\site-packages\pandas\util_decorators.py", line 188, in wrapper return func(args, *kwargs)

raise ValueError('Number of passed names did not match '

From the reddit thread, pandas 0.23.4 is what you used but did not specify that version in the requirements.

That version works.

I would make a requirements.txt  so others will not run into this issue.

**Comment by WenjieZ** [comment]
Thanks for this information. You can edit the `README.md` and make a PR.

**Comment by WenjieZ** [comment]
Solved in #4
