### ISSUE TITLE
massive amount of deprecation warnings when running

### ISSUE THREAD

**Issue by martinsweitzer** [WenjieZ/pokemongo#3]
on pandas 0.23.4   (as that is what seems to work)

>C:\Python3\python.exe pokemongo.py
pokemongo.py:35: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Name'] = pokemon.index[-1]
pokemongo.py:36: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Fast'] = species_moves.iloc[i, j]
pokemongo.py:37: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Charge'] = species_moves.iloc[i, k]
pokemongo.py:38: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Type_F'] = moves.loc[pokemon.iloc[-1].Fast].Type
pokemongo.py:39: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Type_C'] = moves.loc[pokemon.iloc[-1].Charge].Type
pokemongo.py:40: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Power1'] = moves.loc[pokemon.iloc[-1].Fast].Power
pokemongo.py:41: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Energy1'] = moves.loc[pokemon.iloc[-1].Fast].Energy
pokemongo.py:42: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Time1'] = moves.loc[pokemon.iloc[-1].Fast].Duration
pokemongo.py:43: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Stab1'] = 1.2 if pokemon.iloc[-1].Type_F in (pokemon.iloc[-1].Type1, pokemon.iloc[-1].Type2) else 1
pokemongo.py:44: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Power2'] = moves.loc[pokemon.iloc[-1].Charge].Power
pokemongo.py:45: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Energy2'] = moves.loc[pokemon.iloc[-1].Charge].Energy
pokemongo.py:46: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  pokemon.ix[-1, 'Time2'] = moves.loc[pokemon.iloc[-1].Charge].Duration
pokemongo.py:47: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

**Comment by WenjieZ** [comment]
It's expected. Just ignore them.
